### PR TITLE
Standardize logging and error handling (image & filesystem)

### LINKED ISSUE #4: Standardize logging & error handling
1. Remove dependency to `github.com/Sirupsen/logrus`.
2. Only use `log.Print` and friends to print.
3. All functions that might fail must have an `error` type return value as last return value.
4. All caller to funtions that returns `error` must explicitly ignore the error or handle it properly (ie. return it to caller).

Leave comments to specify files / functions you are editing to prevent potential merge conflicts.
```go
if err := SomeFunction(); err != nil {
    return err
}
```

### PR DESCRIPTION
**Pull request by ZongZheng300**

### CODE REVIEW

File: container/init.go [hunk 1]
```diff
@@ -12,58 +12,63 @@ import (
...
 	if err != nil {
-		log.Errorf("Exec loop path error %v", err)
-		return err
+		return fmt.Errorf("fail to search for an executable named file in the dir path : %v", err)
 	}
-	log.Infof("Find path %s", path)
+	log.Printf("Find path %s", path)
 	if err := syscall.Exec(path, cmdArray[0:], os.Environ()); err != nil {
-		log.Errorf(err.Error())
+		return fmt.Errorf(err.Error())
```
Comment (yqszxx) [inline container/init.go:34]:
```suggestion
		return err
```

File: container/init.go [hunk 2]
```diff
@@ -12,58 +12,63 @@ import (
...
+	if err := pivotRoot(pwd); err != nil {
+		return err
+	}
+	//mount proc and dev
 	defaultMountFlags := syscall.MS_NOEXEC | syscall.MS_NOSUID | syscall.MS_NODEV
-	syscall.Mount("proc", "/proc", "proc", uintptr(defaultMountFlags), "")
-
-	syscall.Mount("tmpfs", "/dev", "tmpfs", syscall.MS_NOSUID|syscall.MS_STRICTATIME, "mode=755")
+	if err := syscall.Mount("proc", "/proc", "proc", uintptr(defaultMountFlags), ""); err != nil {
+		return fmt.Errorf(err.Error())
```
Comment (yqszxx) [inline container/init.go:66]:
```suggestion
		return err
```

File: container/init.go (hunk 1 above)
Comment (yqszxx) [inline container/init.go]:
```suggestion
		return err
```

File: container/init.go (hunk 2 above)
Comment (yqszxx) [inline container/init.go]:
```suggestion
		return err
```

File: container/init.go [hunk 3]
```diff
@@ -12,58 +12,63 @@ import (
...
+	}
+	if err := syscall.Mount("tmpfs", "/dev", "tmpfs", syscall.MS_NOSUID|syscall.MS_STRICTATIME, "mode=755"); err != nil {
+		return fmt.Errorf(err.Error())
```
Comment (yqszxx) [inline container/init.go]:
```suggestion
		return err
```

**Review by yqszxx — CHANGES_REQUESTED** [review]
If there's no need for additional comments for an error, just directly return it.

**Review by yqszxx — APPROVED** [review]
LGTM!
